import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient();

const motocargueros = [
  {
    brand: "Vaisand",
    model: "DB 200ZH",
    slug: "vaisand-db-200zh",
    description:
      "Motocarguero de carga de 197 cc diseñado para labores de transporte y trabajo diario.",

    price: new Prisma.Decimal("15990000"),
    stock: 0,

    engineType: "4 tiempos",
    refrigeration: "aire frozado",
    displacement: 197,
    horsepower: new Prisma.Decimal("12.7"),
    maxTorque: new Prisma.Decimal("13.9"),
    transmission: "5 velocidades + reversa + bajo",
    starter: "Eléctrico y pedal",
    loadCapacity: 750,
    fuelTank: new Prisma.Decimal("4.5"),
    frontSuspension: "Telescópica reforzada",
    rearSuspension: "Ballestas de 7 hojas",
    frontBrake: "Disco",
    rearBrake: "Campana",
    bodyDimensions: "1.80 m x 1.20 m",
    tires: "500 x R12",
    equipment:
      "Farola LED, tablero digital y sistema de bajo.",
    image: null,
  },

  {
    brand: "Vaisand",
    model: "DB 250ZH",
    slug: "vaisand-db-250zh",
    description:
      "Motocarguero de 246 cc con refrigeración líquida y capacidad de carga de hasta 850 kg.",

    price: new Prisma.Decimal("18490000"),
    stock: 0,

    engineType: "4 tiempos",
    refrigeration: "líquida",
    displacement: 246,
    horsepower: new Prisma.Decimal("15.4"),
    maxTorque: new Prisma.Decimal("19.0"),
    transmission: "5 velocidades + reversa",
    starter: "Eléctrico y pedal",
    loadCapacity: 850,
    fuelTank: new Prisma.Decimal("4.5"),
    frontSuspension: "Telescópica reforzada",
    rearSuspension: "Ballestas de 7 hojas",
    frontBrake: "Disco",
    rearBrake: "Campana",
    bodyDimensions: "1.90 m x 1.25 m",
    tires: "500 x R12",
    equipment:
      "Refrigeración líquida con radiador, luces LED, tacómetro digital y sistema de bajo.",
    image: null,
  },

  {
    brand: "Vaisand",
    model: "DB 300ZH",
    slug: "vaisand-db-300zh",
    description:
      "Motocarguero de 272 cc y una tonelada de capacidad de carga, equipado con sistema hidráulico para el volco.",

    price: new Prisma.Decimal("24490000"),
    stock: 0,

    engineType: "4 tiempos",
    refrigeration: "Líquida",
    displacement: 272,
    horsepower: new Prisma.Decimal("19"),
    maxTorque: new Prisma.Decimal("21"),
    transmission: "5 velocidades + reversa",
    starter: "Eléctrico y pedal",
    loadCapacity: 1000,
    fuelTank: new Prisma.Decimal("4.5"),
    frontSuspension: "Telescópica reforzada",
    rearSuspension: "Ballestas de 7 hojas",
    frontBrake: "Disco",
    rearBrake: "Campana",
    bodyDimensions: "2.00 m x 1.40 m",
    tires: "500 x R12, doble llanta trasera",
    equipment:
      "Gato hidráulico, doble suspensión delantera, doble llanta trasera y sistema de volco.",
    image: null,
  },

  {
    brand: "Kameyo",
    model: "MTRD 200",
    slug: "kameyo-mtrd-200",
    description:
      "Motocarguero diseñado para labores de logística y transporte diario.",

    price: new Prisma.Decimal("15990000"),
    stock: 0,

    engineType: "4 tiempos, monocilíndrico OHV",
    refrigeration: "aire frozado",
    displacement: 197,
    horsepower: new Prisma.Decimal("14.1"),
    maxTorque: new Prisma.Decimal("17.5"),
    transmission: "5 velocidades + reversa",
    starter: "Eléctrico y pedal",
    loadCapacity: 750,
    fuelTank: null,
    frontSuspension: "Independiente",
    rearSuspension: "Doble amortiguador",
    frontBrake: "Disco hidráulico",
    rearBrake: "Tambor",
    bodyDimensions: null,
    tires: null,
    equipment:
      "Tracción trasera con diferencial.",
    image: null,
  },

  {
    brand: "Kameyo",
    model: "MTRD 250",
    slug: "kameyo-mtrd-250",
    description:
      "Motocarguero de 246 cc diseñado para trabajo pesado en zonas urbanas y rurales.",

    price: new Prisma.Decimal("18490000"),
    stock: 0,

    engineType: "4 tiempos, monocilíndrico OHV",
    refrigeration: "líquida",
    displacement: 246,
    horsepower: new Prisma.Decimal("15.5"),
    maxTorque: new Prisma.Decimal("19.5"),
    transmission: "5 velocidades + reversa + bajo",
    starter: "Eléctrico y pedal",
    loadCapacity: 850,
    fuelTank: new Prisma.Decimal("5"),
    frontSuspension: null,
    rearSuspension: null,
    frontBrake: "Disco hidráulico",
    rearBrake: "Campana",
    bodyDimensions: null,
    tires: null,
    equipment:
      "Refrigeración líquida, chasis reforzado, puerto USB e iluminación frontal y trasera.",
    image: null,
  },

  {
    brand: "Kameyo",
    model: "MTRD 300",
    slug: "kameyo-mtrd-300",
    description:
      "Motocarguero de alta capacidad para trabajo pesado con motor de 296 cc y capacidad de carga de una tonelada.",

    price: new Prisma.Decimal("23790000"),
    stock: 0,

    engineType: "4 tiempos, monocilíndrico OHV",
    displacement: 296,
    horsepower: new Prisma.Decimal("22"),
    maxTorque: new Prisma.Decimal("21"),
    transmission: "5 velocidades + reversa + bajo",
    starter: "Eléctrico y pedal",
    loadCapacity: 1000,
    fuelTank: new Prisma.Decimal("4.5"),
    frontSuspension: "Telescópica reforzada",
    rearSuspension: "Muelles reforzados",
    frontBrake: "Disco hidráulico",
    rearBrake: "Tambor hidráulico",
    bodyDimensions: "2.20 m x 1.40 m de platón",
    tires: "4.50-R12",
    equipment:
      "Volco, farola LED, tablero digital, puerto USB y sistema eléctrico de 12 V.",
    image: null,
  },

  {
    brand: "Kameyo",
    model: "AGR 300",
    slug: "kameyo-agr-300",
    description:
      "Motocarguero utilitario 4x4 diseñado para trabajo pesado y terrenos de alta exigencia.",

    price: new Prisma.Decimal("35990000"),
    stock: 0,

    engineType: "4 tiempos, monocilíndrico OHV",
    refrigeration: "Líquida",
    displacement: 275,
    horsepower: new Prisma.Decimal("17"),
    maxTorque: new Prisma.Decimal("21"),
    transmission: "5 velocidades + reversa",
    starter: null,
    loadCapacity: 1000,
    fuelTank: null,
    frontSuspension: "Reforzada de 11 hojas",
    rearSuspension: "Reforzada de 11 hojas",
    frontBrake: null,
    rearBrake: null,
    bodyDimensions: "1.40 m x 2.20 m de platón expandido",
    tires: null,
    equipment:
      "Tracción 4x4, winche eléctrico, volco eléctrico, cabina con panorámico, iluminación LED y pantalla digital.",
    image: null,
  },

  {
    brand: "AYCO",
    model: "AY200ZH",
    slug: "ayco-ay200zh",
    description:
      "Motocarguero AYCO de 197 cc con refrigeración por aire reforzado y capacidad de carga de 500 kg.",

    price: new Prisma.Decimal("16790000"),
    stock: 0,

    engineType: "4 tiempos ecológico OHV",
    refrigeration: "aire frozado",
    displacement: 197,
    horsepower: new Prisma.Decimal("13"),
    maxTorque: new Prisma.Decimal("13.9"),
    transmission: "5 velocidades + bajo + reversa",
    starter: "Eléctrico y pedal",
    loadCapacity: 750,
    fuelTank: new Prisma.Decimal("5.8"),
    frontSuspension: "Barras telescópicas",
    rearSuspension: "Muelles",
    frontBrake: "Disco",
    rearBrake: "Hidráulico",
    bodyDimensions: "1.75 m x 1.25 m",
    tires: "4.50-12, 8 lonas",
    equipment:
      "Carburador, encendido CDI y transmisión final por cardán.",
    image: null,
  },

  {
    brand: "AYCO",
    model: "AY200ZH-2",
    slug: "ayco-ay200zh-2",
    description:
      "Versión AYCO 200 con refrigeración líquida y capacidad de carga de 500 kg.",

    price: new Prisma.Decimal("17990000"),
    stock: 0,

    engineType: "4 tiempos ecológico OHV",
    refrigeration: "aire forzado",
    displacement: 197,
    horsepower: new Prisma.Decimal("13"),
    maxTorque: new Prisma.Decimal("13.9"),
    transmission: "5 velocidades + bajo + reversa",
    starter: "Eléctrico y pedal",
    loadCapacity: 750,
    fuelTank: new Prisma.Decimal("5.8"),
    frontSuspension: "Barras telescópicas",
    rearSuspension: "Muelles",
    frontBrake: "Disco",
    rearBrake: "Hidráulico",
    bodyDimensions: "1.75 m x 1.25 m",
    tires: "4.50-12, 8 lonas",
    equipment:
      "Refrigeración líquida, carburador, encendido CDI y transmisión final por cardán.",
    image: null,
  },

  {
    brand: "AYCO",
    model: "AY300ZHS",
    slug: "ayco-ay300zhs",
    description:
      "Motocarguero AYCO 300 con platón fijo, motor de 272 cc y capacidad de carga de una tonelada.",

    price: new Prisma.Decimal("23990000"),
    stock: 0,

    engineType: "4 tiempos ecológico OHV",
    refrigeration: "Líquida",
    displacement: 272,
    horsepower: new Prisma.Decimal("19"),
    maxTorque: new Prisma.Decimal("19.5"),
    transmission: "5 velocidades + bajo + reversa",
    starter: "Eléctrico y pedal",
    loadCapacity: 1000,
    fuelTank: new Prisma.Decimal("5.8"),
    frontSuspension: "Barras telescópicas",
    rearSuspension: "Muelles reforzados",
    frontBrake: "Disco",
    rearBrake: "Hidráulico",
    bodyDimensions: "3.16 m x 1.33 m x 1.25 m",
    tires: "4.50-12, 8 lonas",
    equipment:
      "Platón fijo, transmisión final por cardán y encendido CDI.",
    image: null,
  },

  {
    brand: "AYCO",
    model: "AY300ZHV",
    slug: "ayco-ay300zhv",
    description:
      "Motocarguero AYCO 300 tipo volqueta con sistema electrohidráulico de levante.",

    price: new Prisma.Decimal("25990000"),
    stock: 0,

    engineType: "4 tiempos ecológico OHV",
    refrigeration: "Líquida",
    displacement: 272,
    horsepower: new Prisma.Decimal("19"),
    maxTorque: new Prisma.Decimal("19.5"),
    transmission: "5 velocidades + bajo + reversa",
    starter: "Eléctrico y pedal",
    loadCapacity: 1000,
    fuelTank: new Prisma.Decimal("5.8"),
    frontSuspension: "Barras telescópicas",
    rearSuspension: "Muelles reforzados",
    frontBrake: "Disco",
    rearBrake: "Hidráulico",
    bodyDimensions: "1.90 m x 1.40 m de volquete",
    tires: "4.50-12, 8 lonas",
    equipment:
      "Volqueta metálica con accionamiento electrohidráulico mediante botón.",
    image: null,
  },
];


const motosVento = [
  {
    brand: "Vento",
    model: "GTS 300",
    slug: "vento-gts-300",
    warrantyYears: 2,
    colors: ["Gris Mate"],
    engineType: "4 tiempos, refrigerado por aceite",
    displacement: 272.9,
    horsepower: 25,
    horsepowerRpm: 7000,
    maxTorque: 20,
    torqueRpm: 6000,
    compressionRatio: "9:1",
    fuelSupply: "Inyección electrónica",
    ignition: "Eléctrico",
    transmission: "Mecánica de 6 velocidades",
    fuelCapacity: 14,
    lengthMm: 2100,
    widthMm: 860,
    heightMm: 1380,
    seatHeightMm: 810,
    groundClearanceMm: 270,
    weightKg: 126,
    frontSuspension: "Horquilla hidráulica invertida",
    rearSuspension: "Mono suspensión",
    frontBrake: "Disco hidráulico (ABS)",
    rearBrake: "Disco hidráulico",
    frontWheel: "90/90 R19",
    rearWheel: "110/90 R17",
    equipment:
      "USB, alarma, encendido remoto, tablero digital, iluminación full LED, defensa con exploradoras",
  },
  {
    brand: "Vento",
    model: "DAKAR 200S",
    slug: "vento-dakar-200s",
    warrantyYears: 2,
    colors: ["Gris Mate"],
    engineType: "4 tiempos, refrigerado por aire",
    displacement: 196.4,
    horsepower: 16,
    maxTorque: 13,
    torqueRpm: 5500,
    fuelSupply: "Carburador",
    ignition: "CDI electrónica",
    transmission: "Manual de 5 velocidades",
    fuelCapacity: 18.5,
    lengthMm: 2100,
    widthMm: 830,
    heightMm: 1310,
    seatHeightMm: 855,
    groundClearanceMm: 260,
    weightKg: 140,
    frontSuspension: "Horquilla hidráulica invertida",
    rearSuspension: "Mono suspensión",
    frontBrake: "Disco hidráulico (ABS)",
    rearBrake: "Disco hidráulico",
    frontWheel: "90/100 R21",
    rearWheel: "110/100 R18",
    equipment:
      "USB, alarma, encendido remoto, tablero digital, iluminación full LED, defensa con exploradoras",
  },
  {
    brand: "Vento",
    model: "CROSSMAX PRO 200",
    slug: "vento-crossmax-pro-200",
    warrantyYears: 2,
    colors: ["Negro Brillante"],
    engineType: "4 tiempos, refrigerado por aire",
    displacement: 196.4,
    horsepower: 16,
    horsepowerRpm: 7000,
    maxTorque: 13,
    torqueRpm: 5500,
    compressionRatio: "9,2:1",
    fuelSupply: "Carburador",
    ignition: "Eléctrico y de pedal",
    transmission: "Mecánica de 5 velocidades",
    fuelCapacity: 12,
    lengthMm: 2120,
    widthMm: 840,
    heightMm: 1120,
    seatHeightMm: 850,
    groundClearanceMm: 200,
    weightKg: 132,
    frontSuspension: "Horquilla hidráulica invertida",
    rearSuspension: "Mono suspensión",
    frontBrake: "Disco hidráulico (ABS)",
    rearBrake: "Disco",
    frontWheel: "90/100/21",
    rearWheel: "110/100/18",
    equipment:
      "USB, alarma, encendido remoto, tablero digital, iluminación full LED, defensa con exploradoras",
  },
  {
    brand: "Vento",
    model: "OVNI TRACK 125",
    slug: "vento-ovni-track-125",
    warrantyYears: 2,
    colors: ["Negro Brillante"],
    engineType: "4 tiempos, refrigerado por aire forzado",
    displacement: 125.1,
    horsepower: 8.1,
    horsepowerRpm: 7500,
    maxTorque: 7.5,
    torqueRpm: 6000,
    fuelSupply: "Carburador",
    ignition: "CDI electrónica",
    transmission: "Automática CVT",
    fuelCapacity: 4.5,
    lengthMm: 1790,
    widthMm: 760,
    heightMm: 1070,
    seatHeightMm: 760,
    weightKg: 95,
    frontSuspension: "Horquilla hidráulica",
    rearSuspension: "Amortiguador con resorte",
    frontBrake: "Disco",
    rearBrake: "Tambor combinado CBS",
    frontWheel: "90/90-R12",
    rearWheel: "3.50-R10",
    equipment:
      "USB, alarma, encendido remoto, sistema VenTec, bodega bajo el asiento, luces LED, defensas, luces exploradoras y sliders",
  },
  {
    brand: "Vento",
    model: "SCREAMER 250",
    slug: "vento-screamer-250",
    warrantyYears: 2,
    colors: ["Azul Navy Mate", "Negro Mate"],
    engineType: "4 tiempos, refrigerado por aceite",
    displacement: 223,
    horsepower: 20,
    horsepowerRpm: 7500,
    maxTorque: 16,
    torqueRpm: 6500,
    compressionRatio: "9,2:1",
    fuelSupply: "Inyección electrónica",
    ignition: "Eléctrico y de pedal",
    transmission: "Mecánica de 6 velocidades",
    fuelCapacity: 20,
    lengthMm: 2000,
    widthMm: 760,
    heightMm: 1150,
    seatHeightMm: 800,
    groundClearanceMm: 170,
    weightKg: 135,
    frontSuspension: "Horquilla hidráulica invertida",
    rearSuspension: "Mono suspensión",
    frontBrake: "Disco hidráulico (ABS)",
    rearBrake: "Disco",
    frontWheel: "90/90/17",
    rearWheel: "130/70/17",
    equipment:
      "USB, alarma, encendido remoto, tablero digital, iluminación full LED, defensa con exploradoras",
  },
  {
    brand: "Vento",
    model: "FALKON 125",
    slug: "vento-falkon-125",
    warrantyYears: 2,
    colors: ["Negro Mate"],
    engineType: "4 tiempos, refrigerado por aire",
    displacement: 120,
    horsepower: 10,
    horsepowerRpm: 8000,
    maxTorque: 6.9,
    torqueRpm: 6000,
    compressionRatio: "9,2:1",
    fuelSupply: "Carburador",
    ignition: "Eléctrico y de pedal",
    transmission: "Semi-automática de 4 velocidades",
    fuelCapacity: 3.5,
    lengthMm: 1900,
    widthMm: 670,
    heightMm: 1080,
    seatHeightMm: 790,
    weightKg: 97,
    frontSuspension: "Horquilla hidráulica",
    rearSuspension: "Doble amortiguador",
    frontBrake: "Disco",
    rearBrake: "Tambor combinado CBS",
    frontWheel: "Rin de aluminio 2.5 R17",
    rearWheel: "Rin de aluminio 3.0 R16",
    equipment:
      "USB, alarma, encendido remoto, sistema VenTec, bodega bajo el asiento",
  },
  {
    brand: "Vento",
    model: "RAPID 125",
    slug: "vento-rapid-125",
    warrantyYears: 2,
    colors: ["Gris Plata"],
    engineType: "4 tiempos, refrigerado por aire",
    displacement: 120,
    horsepower: 10,
    horsepowerRpm: 8000,
    maxTorque: 6.9,
    torqueRpm: 6000,
    compressionRatio: "9,2:1",
    fuelSupply: "Carburador",
    ignition: "Eléctrico y de pedal",
    transmission: "Semi-automática de 4 velocidades",
    fuelCapacity: 3.5,
    lengthMm: 1900,
    widthMm: 670,
    heightMm: 1080,
    seatHeightMm: 790,
    weightKg: 97,
    frontSuspension: "Horquilla hidráulica",
    rearSuspension: "Doble amortiguador",
    frontBrake: "Disco",
    rearBrake: "Tambor combinado CBS",
    frontWheel: "Rin de aluminio 2.5 R17",
    rearWheel: "Rin de aluminio 3.0 R16",
    equipment:
      "USB, alarma, encendido remoto, sistema VenTec, bodega bajo el asiento",
  },
  {
    brand: "Vento",
    model: "OVNI 125",
    slug: "vento-ovni-125",
    warrantyYears: 2,
    colors: ["Negro Mate"],
    engineType: "4 tiempos, refrigerado por aire forzado",
    displacement: 125.1,
    horsepower: 8.1,
    horsepowerRpm: 7500,
    maxTorque: 7.5,
    torqueRpm: 6000,
    fuelSupply: "Carburador",
    ignition: "CDI electrónica",
    transmission: "Automática CVT",
    fuelCapacity: 4.5,
    lengthMm: 1790,
    widthMm: 760,
    heightMm: 1070,
    seatHeightMm: 760,
    weightKg: 95,
    frontSuspension: "Horquilla hidráulica",
    rearSuspension: "Amortiguador con resorte",
    frontBrake: "Disco",
    rearBrake: "Tambor combinado CBS",
    frontWheel: "90/90-R12",
    rearWheel: "3.50-R10",
    equipment:
      "USB, alarma, encendido remoto, sistema VenTec, bodega bajo el asiento y luces LED",
  },
  {
    brand: "Vento",
    model: "PRESLEY 200",
    slug: "vento-presley-200",
    warrantyYears: 2,
    colors: ["Negro Brillante"],
    engineType: "4 tiempos, refrigerado por aire",
    displacement: 181.2,
    horsepower: 16,
    horsepowerRpm: 8500,
    maxTorque: 12.5,
    torqueRpm: 6500,
    compressionRatio: "9,5:1",
    fuelSupply: "Carburador",
    ignition: "Eléctrico y de pedal",
    transmission: "Mecánica de 5 velocidades",
    fuelCapacity: 10,
    lengthMm: 2000,
    widthMm: 830,
    heightMm: 1100,
    seatHeightMm: 770,
    groundClearanceMm: 150,
    weightKg: 105,
    frontSuspension: "Horquilla hidráulica",
    rearSuspension: "Doble amortiguador",
    frontBrake: "Disco hidráulico (ABS)",
    rearBrake: "Tambor",
    frontWheel: "90/90/17",
    rearWheel: "120/80/17",
    equipment:
      "USB, alarma, encendido remoto, sistema VenTec y faros LED",
  },
  {
    brand: "Vento",
    model: "SPIRIT ZX 125",
    slug: "vento-spirit-zx-125",
    warrantyYears: 2,
    colors: ["Negro Mate", "Rojo"],
    engineType: "4 tiempos, refrigerado por aire",
    displacement: 124.6,
    horsepower: 8.1,
    horsepowerRpm: 7000,
    maxTorque: 7.5,
    torqueRpm: 6000,
    compressionRatio: "9,2:1",
    fuelSupply: "Carburador",
    ignition: "Eléctrico y de pedal",
    transmission: "Automática CVT",
    fuelCapacity: 5,
    lengthMm: 1840,
    widthMm: 750,
    heightMm: 1080,
    seatHeightMm: 750,
    weightKg: 97,
    frontSuspension: "Horquilla hidráulica",
    rearSuspension: "Mono suspensión",
    frontBrake: "Disco",
    rearBrake: "Tambor combinado CBS",
    frontWheel: "3.5 R10",
    rearWheel: "3.5 R10",
    equipment:
      "USB, alarma, encendido remoto, sistema VenTec, bodega bajo el asiento e incluye baúl",
  },
  {
    brand: "Vento",
    model: "ALPINA 300",
    slug: "vento-alpina-300",
    warrantyYears: 2,
    colors: ["Gris Plata"],
    engineType: "4 tiempos, refrigerado por aceite",
    displacement: 277.7,
    horsepower: 28,
    horsepowerRpm: 8500,
    maxTorque: 24,
    torqueRpm: 6000,
    compressionRatio: "9,2:1",
    fuelSupply: "Inyección electrónica",
    ignition: "Eléctrico",
    transmission: "Mecánica de 6 velocidades",
    fuelCapacity: 14,
    lengthMm: 2070,
    widthMm: 900,
    heightMm: 1360,
    seatHeightMm: 810,
    groundClearanceMm: 160,
    weightKg: 150,
    frontSuspension: "Horquilla hidráulica invertida",
    rearSuspension: "Mono suspensión",
    frontBrake: "Disco hidráulico (ABS)",
    rearBrake: "Disco",
    frontWheel: "110/80/17",
    rearWheel: "140/70/17",
    equipment:
      "USB, alarma, encendido remoto, tablero digital, iluminación full LED y defensa con exploradoras",
    certifications:
      "Sistema de frenos ABS, encendido automático de luces, luces de circulación diurna, EURO 3",
  },
  {
    brand: "Vento",
    model: "LITHIUM 4.0 125",
    slug: "vento-lithium-4-0-125",
    warrantyYears: 2,
    colors: ["Negro Mate", "Naranja"],
    engineType: "4 tiempos, refrigerado por aire",
    displacement: 124.8,
    horsepower: 11,
    horsepowerRpm: 8500,
    maxTorque: 9.2,
    torqueRpm: 7500,
    compressionRatio: "9,0:1",
    fuelSupply: "Carburador",
    ignition: "Eléctrico y de pedal",
    transmission: "Mecánica de 5 velocidades",
    fuelCapacity: 10,
    lengthMm: 1960,
    widthMm: 750,
    heightMm: 1025,
    seatHeightMm: 750,
    groundClearanceMm: 130,
    weightKg: 107,
    frontSuspension: "Horquilla hidráulica",
    rearSuspension: "Doble amortiguador",
    frontBrake: "Disco",
    rearBrake: "Tambor combinado CBS",
    frontWheel: "90/90/18",
    rearWheel: "90/100/18",
    equipment: "USB, alarma, encendido remoto y sistema VenTec",
  },
];

async function main() {
  console.log("🏍️ Cargando motocargueros...");

  for (const motocarro of motocargueros) {
    await prisma.motocarro.upsert({
      where: {
        slug: motocarro.slug,
      },
      update: motocarro,
      create: motocarro,
    });
  }

  console.log(
    `✅ Se cargaron/actualizaron ${motocargueros.length} motocargueros.`
  );

  console.log("🏍️ Cargando motos Vento...");

  for (const moto of motosVento) {
    await prisma.moto.upsert({
      where: {
        slug: moto.slug,
      },
      update: moto,
      create: moto,
    });
  }

  console.log(
    `✅ Se cargaron/actualizaron ${motosVento.length} motos Vento.`
  );

  console.log("🎉 Seed completado correctamente.");
}

main()
  .catch((error) => {
    console.error("Error durante el seed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
